export {createFakeAgent, responses, parseRequest} from './api.ts'
export {ElizaBot, elizaResponder, formatElizaResponse} from './presets/eliza.ts'
export {formatSarcasticResponse, sarcasticResponder} from './presets/sarcastic.ts'
export type {FakeAgent, ParsedRequest, ParsedProtocol, CreateFakeAgentOptions} from './api.ts'
export type {AgentName, AgentConfig} from './agents.ts'
