export {createDumbAgent, responses, parseRequest} from './api.ts'
export {ElizaBot, elizaResponder, formatElizaResponse} from './presets/eliza.ts'
export {formatSarcasticResponse, sarcasticResponder} from './presets/sarcastic.ts'
export {extractToolResult, parseSimulatedToolCommand, readFileToolCall, simulateToolCall, withSimulatedToolCalls} from './tools.ts'
export type {DumbAgent, ParsedRequest, ParsedProtocol, CreateDumbAgentOptions} from './api.ts'
export type {AgentName, AgentConfig} from './agents.ts'
export type {DumbAgentFetch, SimulatedToolCall, SimulatedToolCommand} from './tools.ts'
